<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class WeldingCompleteData extends Model
{
    use HasFactory;

    protected $fillable = [
        'ProcessOrderID',
        'weld_map_issued',
        'link_to_weld_map',
        'weld_procedure_qualification',
        'link_to_pqr',
        'weld_procedure_specifications',
        'link_to_wps',
        'welder_performance_qualification',
        'link_to_wpq',
        'welding_wire',
        'link_to_wire_certificate',
        'shielding_gas',
        'link_to_gas_data_sheet',
        'pre_weld_inspection',
        'inspection_during_welding',
        'post_weld_inspection',
        'sign_off_welding_complete',
        'comments_welding_complete',
        'status',
        'quantity',
        // Add other fields as needed
    ];

    protected $table = '-- Create the User table
    CREATE TABLE [User] (
        ID INT PRIMARY KEY IDENTITY,
        FirstName NVARCHAR(50),
        LastName NVARCHAR(50),
        Department NVARCHAR(50),
        ClockNumber NVARCHAR(50),
        Login NVARCHAR(100)
    );
    
    -- Insert values into the User table
    INSERT INTO [User] (FirstName, LastName, Department, ClockNumber)
    VALUES
    ('John', 'Larkin', '01-Fabrication 1', '14'),
    ('James', 'Ennis', '01-Fabrication 1', '29'),
    ('John', 'French', '01-Fabrication 1', '33'),
    ('Eamonn', 'Maloney', '01-Fabrication 1', '61'),
    ('Patrick', 'Barnes', '01-Fabrication 1', '74'),
    ('Adrian', 'Burford', '01-Fabrication 1', '85'),
    ('Derek', 'O Brien', '01-Fabrication 1', '102'),
    ('Festus', 'Ebosele', '01-Fabrication 1', '109'),
    ('Darragh', 'Connor', '01-Fabrication 1', '155'),
    ('Paul', 'Murphy', '01-Fabrication 1', '179'),
    ('Thomas', 'Mahon', '01-Fabrication 1', '217'),
    ('Jim', 'Nolan', '01-Fabrication 1', '218'),
    ('Dermot', 'Frayne', '01-Fabrication 1', '219'),
    ('Mark', 'Crosbie', '01-Fabrication 1', '220'),
    ('Killian', 'Connor', '01-Fabrication 1', '232'),
    ('Daniel', 'Carroll', '01-Fabrication 1', '233'),
    ('Jason', 'Murphy', '01-Fabrication 1', '243'),
    ('Seamus', 'Sinnott', '01-Fabrication 1', '246'),
    ('Paul', 'Cummins', '01-Fabrication 1', '283'),
    ('Daniel', 'Kearns', '01-Fabrication 1', '288'),
    ('Leanne', 'Furlong', '01-Fabrication 1', '289'),
    ('Adam', 'Kelly', '01-Fabrication 1', '290'),
    ('James', 'Murphy', '01-Fabrication 1', '294'),
    ('Shane', 'Doran', '01-Fabrication 1', '312'),
    ('Ben', 'O Brien', '01-Fabrication 1', '347'),
    ('David', 'Meyler', '01-Fabrication 1', '350'),
    ('Nathan', 'O Brien', '01-Fabrication 1', '369'),
    ('Jason', 'Donovan', '01-Fabrication 1', '375'),
    ('Danny', 'Lawton Corish', '01-Fabrication 1', '404'),
    ('Stephen', 'Reilly', '01-Fabrication 1', '409'),
    ('James', 'O Leary', '01-Fabrication 1', '410'),
    ('Alan', 'McEvoy', '01-Fabrication 1', '419'),
    ('Dean', 'O Leary', '01-Fabrication 1', '420'),
    ('Ger', 'Lynch', '01-Fabrication 1', '424'),
    ('Pierce', 'Murphy', '01-Fabrication 1', '425'),
    ('Edgars', 'Locmelis', '01-Fabrication 1', '427'),
    ('Cian', 'Anthony Byrne', '01-Fabrication 1', '431'),
    ('David', 'Collins', '01-Fabrication 1', '432'),
    ('Jack', 'Kennedy', '01-Fabrication 1', '433'),
    ('Kyle', 'Meyler', '01-Fabrication 1', '441'),
    ('Keith', 'Whitty', '01-Fabrication 1', '444'),
    ('Niall', 'Roche', '01-Fabrication 1', '449'),
    ('Test', 'Person', '01-Fabrication 1', '888'),
    ('Adrian', 'Dooley', '02-Material Prep', '23'),
    ('Derek', 'Long', '02-Material Prep', '40'),
    ('Jonathan', 'Mythen', '02-Material Prep', '44'),
    ('Patrick', 'Murphy', '02-Material Prep', '58'),
    ('John', 'Dooley', '02-Material Prep', '163'),
    ('Tony', 'Byrne', '02-Material Prep', '239'),
    ('Anthony', 'Roche', '02-Material Prep', '256'),
    ('Brian', 'Murphy', '02-Material Prep', '273'),
    ('Craig', 'Kehoe', '02-Material Prep', '300'),
    ('Tony', 'Moran', '02-Material Prep', '309'),
    ('Cian', 'Byrne', '02-Material Prep', '315'),
    ('Keith', 'Donovan', '02-Material Prep', '317'),
    ('Gary', 'Moorhead', '02-Material Prep', '380'),
    ('David', 'Millar', '02-Material Prep', '384'),
    ('Arek', 'Bobrowski', '02-Material Prep', '392'),
    ('Lukasz', 'Wasilewski', '02-Material Prep', '396'),
    ('Philip', 'Byrne', '02-Material Prep', '401'),
    ('Padraig', 'Cousins', '02-Material Prep', '407'),
    ('Jim', 'Fallon', '02-Material Prep', '426'),
    ('Victor', 'Murphy', '02-Material Prep', '505'),
    ('Ivan', 'Donoghue', '03-HR', '532'),
    ('Jamie', 'Kent', '04-Supply Chain', '522'),
    ('Aideen', 'Clancy', '04-Supply Chain', '558'),
    ('Emmet', 'Dunne', '04-Supply Chain', '596'),
    ('Emma', 'Flood', '04-Supply Chain', '613'),
    ('Agnes', 'Malone', '07-Maintenance', '76'),
    ('David', 'Berney', '07-Maintenance', '148'),
    ('David', 'Murphy', '07-Maintenance', '152'),
    ('Padraig', 'Donohoe', '07-Maintenance', '204'),
    ('Sean', 'Kent', '07-Maintenance', '552'),
    ('Kacper', 'Sobieraj', '07-Maintenance', '619'),
    ('Conor', 'Boylan', '13-Engineering - Bespoke Products', '517'),
    ('Sean', 'O Brien', '13-Engineering - Bespoke Products', '530'),
    ('Olga', 'Donoghue', '13-Engineering - Bespoke Products', '543'),
    ('Arkadiusz', 'Morawiak', '13-Engineering - Bespoke Products', '556'),
    ('Ryan', 'Murphy', '13-Engineering - Bespoke Products', '572'),
    ('David', 'Lehnardt', '13-Engineering - Bespoke Products', '595'),
    ('Ahmed', 'Touami', '13-Engineering - Bespoke Products', '610'),
    ('Micheal', 'Curtis', '13-Engineering - Bespoke Products', '612'),
    ('Jack', 'Carley', '13-Engineering - Bespoke Products', '614'),
    ('Suha', 'Cakmak', '13-Engineering - Bespoke Products', '615'),
    ('Mark', 'Delahunty', '13-Engineering - Bespoke Products', '616'),
    ('Dipanjan', 'Saha', '13-Engineering - Bespoke Products', '623'),
    ('Stephen', 'Smith', '13-Engineering - Bespoke Products', '625'),
    ('Patrick', 'O Hagan', '13-Engineering - Bespoke Products', '632'),
    ('Attila', 'Tobias', '13-Engineering - Bespoke Products', '636'),
    ('Colm', 'Whelan', '28-Engineering - Drainage', '525'),
    ('John', 'Barry Reidy', '28-Engineering - Drainage', '567'),
    ('Joseph', 'Ring', '28-Engineering - Drainage', '581'),
    ('Robert', 'Edwards', '28-Engineering - Drainage', '605'),
    ('Catherine', 'Kinsella', '28-Engineering - Drainage', '606'),
    ('Milana', 'Moleva', '28-Engineering - Drainage', '622'),
    ('Peadair', 'Cowman', '28-Engineering - Drainage', '638'),
    ('Roy', 'Ryan', '29-Engineering - EC & Machine Build', '507'),
    ('James', 'Whelan', '29-Engineering - EC & Machine Build', '519'),
    ('Michael', 'Quinn', '29-Engineering - EC & Machine Build', '539'),
    ('Donal', 'Delaney', '29-Engineering - EC & Machine Build', '557'),
    ('Darragh', 'Kelly', '29-Engineering - EC & Machine Build', '576'),
    ('Roman', 'Pitka', '29-Engineering - EC & Machine Build', '582'),
    ('Jason', 'Webster', '29-Engineering - EC & Machine Build', '593'),
    ('Margaret', 'Codd', '29-Engineering - EC & Machine Build', '599'),
    ('Conor', 'Clarke', '29-Engineering - EC & Machine Build', '600'),
    ('Declan', 'Walshe', '29-Engineering - EC & Machine Build', '607'),
    ('Daniel', 'Beltran Rossi', '29-Engineering - EC & Machine Build', '611'),
    ('Dheeraj', 'Sharma', '29-Engineering - EC & Machine Build', '618'),
    ('Zachary', 'Lyons', '29-Engineering - EC & Machine Build', '633'),
    ('Denis', 'Zottin', '29-Engineering - EC & Machine Build', '635'),
    ('Kevin', 'Barry', '29-Engineering - EC & Machine Build', '639'),
    ('Ebin', 'Thomas', '29-Engineering - EC & Machine Build', '641'),
    ('Patrick', 'Doyle', '30-Engineering - R&D', '589'),
    ('Johnny', 'Day', '30-Engineering - R&D', '604'),
    ('Cuneguines', 'Nixon', '30-Engineering - R&D', '609'),
    ('Rafael', 'Saturno', '30-Engineering - R&D', '627'),
    ('Diego', 'Pompeu', '30-Engineering - R&D', '628'),
    ('Patrick', 'O Connor', '31-Supply Chain 2', '231'),
    ('Graham', 'Kelly', '31-Supply Chain 2', '363'),
    ('Sean', 'Doyle', '31-Supply Chain 2', '387'),
    ('James', 'Donegan', '31-Supply Chain 2', '413'),
    ('Aidan', 'Roche', '31-Supply Chain 2', '440'),
    ('Jakub', 'Wasilewski', '31-Supply Chain 2', '446'),
    ('Carl', 'Murphy', '31-Supply Chain 2', '523'),
    ('Eamonn', 'Donovan', '32-Manufacturing Team', '53'),
    ('Dean', 'Maloney', '32-Manufacturing Team', '196'),
    ('JJ', 'Keating', '32-Manufacturing Team', '221'),
    ('Brian', 'Kent', '32-Manufacturing Team', '503'),
    ('James', 'Berney', '32-Manufacturing Team', '513'),
    ('Sean', 'O Brien', '32-Manufacturing Team', '602'),
    ('Jack', 'Rossiter', '34-Commercial Dept', '439'),
    ('Kushan', 'Fernando', '34-Commercial Dept', '629'),
    ('Thibaut', 'Delangle', '34-Commercial Dept', '634'),
    ('Damien', 'Donovan', '70-Fabrication 2', '24'),
    ('Michael', 'Duggan', '70-Fabrication 2', '27'),
    ('Anthony', 'Hayes', '70-Fabrication 2', '37'),
    ('Aidan', 'O Toole', '70-Fabrication 2', '95'),
    ('Finbar', 'Buttimer', '70-Fabrication 2', '176'),
    ('John', 'Walsh', '70-Fabrication 2', '229'),
    ('Alex', 'O Connor', '70-Fabrication 2', '254'),
    ('Lorcan', 'Cummins', '70-Fabrication 2', '267'),
    ('Brendan', 'Carroll', '70-Fabrication 2', '269'),
    ('Shane', 'Murray', '70-Fabrication 2', '292'),
    ('Rees', 'Broaders', '70-Fabrication 2', '306'),
    ('Eddie', 'Moran', '70-Fabrication 2', '310'),
    ('Dylan', 'Moran', '70-Fabrication 2', '338'),
    ('Francis', 'Moran', '70-Fabrication 2', '339'),
    ('Johan', 'De Hoogh', '70-Fabrication 2', '345'),
    ('Wojciech', 'Stypula', '70-Fabrication 2', '348'),
    ('Piotr', 'Stypula', '70-Fabrication 2', '349'),
    ('Vincent', 'Bastardie', '70-Fabrication 2', '351'),
    ('Jason', 'Kelly', '70-Fabrication 2', '357'),
    ('Maciej', 'Dluzynski', '70-Fabrication 2', '359'),
    ('Shane', 'Kelly', '70-Fabrication 2', '362'),
    ('Jason', 'Bradley', '70-Fabrication 2', '383'),
    ('Simon', 'Leacy', '70-Fabrication 2', '386'),
    ('Sreejith', 'Therattil Ravi', '70-Fabrication 2', '389'),
    ('Christopher', 'Curran', '70-Fabrication 2', '393'),
    ('Joshua', 'Furlong', '70-Fabrication 2', '403'),
    ('Jay', 'Storm Graham', '70-Fabrication 2', '411'),
    ('Thomas', 'Leacy', '70-Fabrication 2', '416'),
    ('Conor', 'Barry', '70-Fabrication 2', '417'),
    ('Bobby', 'Connolly', '70-Fabrication 2', '421'),
    ('Philip', 'Roche', '70-Fabrication 2', '434'),
    ('Cian', 'Fallon', '70-Fabrication 2', '435'),
    ('Anthony', 'Doyle', '70-Fabrication 2', '436'),
    ('Michael', 'Cahill', '70-Fabrication 2', '442'),
    ('Stephen', 'Byrne', '70-Fabrication 2', '443'),
    ('Ronan', 'Prendergast', '70-Fabrication 2', '445'),
    ('Adam', 'O Leary Stacey', '70-Fabrication 2', '447'),
    ('Michael', 'Gibbons', '70-Fabrication 2', '448'),
    ('Adam', 'Prendergast', '70-Fabrication 2', '450');
    
    -- Update Login column with the required format (lastname + first letter of firstname)
    UPDATE [User]
    SET Login = LOWER(CONCAT(LastName, LEFT(FirstName, 1)));
    
    -- Display the contents of the User table
    SELECT * FROM [User];
    ';
}


